# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZPSx7q_Z8sycYP041lEOu1JsA-_nzPE

# **Revisão de NumPy**
"""

import numpy as np

vetor = np.array([9, 2, 3, 4, 5])

vetor

type(vetor)

#dir(vetor)

vetor.shape

vetor.size

vetor.dtype

matriz = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

matriz

matriz1 = np.array([[1, 3, 4], [4, 5, 6], [1, 2, 3]])

matriz2 = np.array([[2, 1, 0], [5, 7, 11], [12, 13, 0]])

matriz1 + matriz2

constante = 4
constante * matriz1

np.dot(matriz1, matriz2)

np.zeros(shape = (3, 3))

matriz1.shape

np.zeros(shape = 10)

np.zeros(shape = (3, 4))

np.identity(3)

vetor = np.random.randint(low = 50, high = 2000, size = 100)

vetor

vetor.size

vetor.min()

vetor.max()

vetor.mean()

vetor.std()

vetor = np.random.normal(10, 0.5, 10_000)

vetor

import matplotlib.pyplot as plt

plt.plot(vetor)
plt.show()

import seaborn as sns

sns.histplot(vetor)
plt.show()

matriz = np.random.normal(10, 2.5, size = (4,3))

matriz

