# -*- coding: utf-8 -*-
"""Ambiente_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JKmcOZbW6hfHpjWtSJdAOrvMTnQp9C-
"""

!pip list

print('Hello World!')

import pandas as pd

df = pd.read_csv('Salary_Data.csv')

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['YearsExperience'], df['Salary'])
plt.xlabel('Anos de experiência')
plt.ylabel('Salário')
plt.show()

import numpy as np

vetor = np.array([1, 2, 99, 3, 4])

vetor

!pip install plotly

#hello pltly

vetor1 = np.random.normal(10, 0.5, 50)
vetor2 = np.random.randint(1, 100, 50)

vetor1

vetor2

import plotly.express as px

fig = px.scatter(x = vetor1, y = vetor2)
fig.show()